### ISSUE TITLE
New version of Terraform is available

### ISSUE THREAD

**Issue by pwhittak-24-8** [ibm-cloud-docs/ibm-cloud-provider-for-terraform#5] opened 2020-09-21 23:23 UTC
Does documentation need to be updated from Terraform v0.12.x to Terraform v0.13.x?
https://cloud.ibm.com/docs/terraform?topic=terraform-getting-started
![image](https://user-images.githubusercontent.com/60409298/93825993-4d15e180-fc34-11ea-8772-d88c3eb525e5.png)

Side note I had trouble installing and running the version from https://releases.hashicorp.com/terraform/
I ended up using `brew install terraform`
![image](https://user-images.githubusercontent.com/60409298/93826502-5f444f80-fc35-11ea-8321-1c7e302c5a54.png)
![image](https://user-images.githubusercontent.com/60409298/93831036-ccf57900-fc3f-11ea-9178-56fc9dccc4ba.png)

**Comment by geethasathyamurthy** [comment] 2021-11-11 15:48
@pwhittak-24-8 
Request to close this issue, if it is fixed as per the raised issue.

Thanks,
Geetha

**Comment by geethasathyamurthy** [comment] 2021-11-12 18:37
@pwhittak-24-8 

Currently closing this issue, if you see the issue is not fixed, request to reopen the issue.

Thanks,
Geetha

**Closed as completed by geethasathyamurthy** 2021-11-12 18:37 UTC
